export const TEMPLATES = [
  // ─── Educational Templates ───────────────────────────────────────────
  {
    id: 'contrarian_insight',
    name: 'Contrarian Insight',
    category: 'educational',
    description: 'Challenge a widely held belief in your niche',
    hook_pattern: 'Hot take: [common belief] is wrong.',
    body_pattern: 'Here\'s what actually works:\n\n[explanation]\n\n[better approach]',
    cta_pattern: 'Agree or disagree? Tell me below.',
    best_for: ['authority', 'engagement'],
    tone_modifiers: ['bold', 'contrarian'],
  },
  {
    id: 'framework_3_step',
    name: '3-Step Framework',
    category: 'educational',
    description: 'Teach a simple repeatable process',
    hook_pattern: 'The [outcome] system nobody teaches you:',
    body_pattern: '1. [step one]\n2. [step two]\n3. [step three]\n\n[insight]',
    cta_pattern: 'Save this for your next [session].',
    best_for: ['authority', 'saves'],
    tone_modifiers: ['practical', 'instructional'],
  },
  {
    id: 'common_mistake',
    name: 'Common Mistake',
    category: 'educational',
    description: 'Call out the mistake most people make',
    hook_pattern: 'The biggest mistake I see in [topic]:',
    body_pattern: '[mistake description]\n\nWhat to do instead:\n\n[fix]',
    cta_pattern: 'Bookmark this before your next [action].',
    best_for: ['authority', 'trust'],
    tone_modifiers: ['empathetic', 'direct'],
  },
  {
    id: 'myth_vs_truth',
    name: 'Myth vs Truth',
    category: 'educational',
    description: 'Debunk a common myth with the real truth',
    hook_pattern: 'The [topic] myth that\'s costing you [outcome]:',
    body_pattern: 'Myth: [common belief]\n\nTruth: [reality]\n\n[why it matters]',
    cta_pattern: 'Which myth did you believe? Drop it below.',
    best_for: ['authority', 'engagement'],
    tone_modifiers: ['educational', 'clear'],
  },
  {
    id: 'checklist',
    name: 'Checklist',
    category: 'educational',
    description: 'Provide a quick scannable checklist',
    hook_pattern: 'Your [outcome] checklist (steal this):',
    body_pattern: '✓ [item 1]\n✓ [item 2]\n✓ [item 3]\n✓ [item 4]\n\n[closing insight]',
    cta_pattern: 'Save this. You\'ll want it.',
    best_for: ['saves', 'authority'],
    tone_modifiers: ['practical', 'helpful'],
  },
  {
    id: 'before_after',
    name: 'Before vs After',
    category: 'educational',
    description: 'Show transformation from before to after applying advice',
    hook_pattern: 'Before vs after [implementing something]:',
    body_pattern: 'Before: [negative state]\nAfter: [positive outcome]\n\nThe difference? [key insight]',
    cta_pattern: 'What changed for you? Reply below.',
    best_for: ['authority', 'relatability'],
    tone_modifiers: ['story-driven', 'transformative'],
  },
  {
    id: 'lessons_learned',
    name: 'Lessons Learned',
    category: 'educational',
    description: 'Share hard-won lessons from experience',
    hook_pattern: 'After [time/experience], here\'s what I learned:',
    body_pattern: '[lesson 1]\n[lesson 2]\n[lesson 3]\n\nThe one that changed everything: [key lesson]',
    cta_pattern: 'Which hits hardest? Let me know.',
    best_for: ['authority', 'relatability'],
    tone_modifiers: ['personal', 'insightful'],
  },
  {
    id: 'simple_process',
    name: 'Simple Process',
    category: 'educational',
    description: 'Break down something complex into a simple process',
    hook_pattern: 'Nobody told me [topic] was this simple:',
    body_pattern: 'Step 1: [action]\nStep 2: [action]\nStep 3: [action]\n\nThat\'s it. [outcome].',
    cta_pattern: 'Follow for more systems like this.',
    best_for: ['authority', 'follows'],
    tone_modifiers: ['clear', 'empowering'],
  },

  // ─── Engagement Templates ─────────────────────────────────────────────
  {
    id: 'hot_take',
    name: 'Hot Take',
    category: 'engagement',
    description: 'Share a spicy unpopular opinion to spark debate',
    hook_pattern: 'Unpopular opinion:',
    body_pattern: '[bold statement]\n\n[reasoning]\n\n[implication]',
    cta_pattern: 'Agree or disagree? I want your take.',
    best_for: ['engagement', 'debate'],
    tone_modifiers: ['bold', 'provocative'],
  },
  {
    id: 'agree_disagree',
    name: 'Agree / Disagree',
    category: 'engagement',
    description: 'Present two sides and ask for audience alignment',
    hook_pattern: 'Two camps on [topic]:',
    body_pattern: 'Camp A: [perspective one]\nCamp B: [perspective two]\n\n[your take]',
    cta_pattern: 'Which camp are you in?',
    best_for: ['engagement', 'comments'],
    tone_modifiers: ['balanced', 'curious'],
  },
  {
    id: 'prediction',
    name: 'Prediction',
    category: 'engagement',
    description: 'Make a bold prediction about the future of your niche',
    hook_pattern: 'My prediction for [topic] in [timeframe]:',
    body_pattern: '[prediction]\n\nWhy:\n[reasoning 1]\n[reasoning 2]\n\n[call to reflect]',
    cta_pattern: 'Do you agree? What am I missing?',
    best_for: ['engagement', 'authority'],
    tone_modifiers: ['confident', 'forward-looking'],
  },
  {
    id: 'trend_reaction',
    name: 'Trend Reaction',
    category: 'engagement',
    description: 'React to a trending topic with your unique angle',
    hook_pattern: 'Everyone\'s talking about [trend]. Here\'s what they\'re missing:',
    body_pattern: '[what most people say]\n\nBut the real insight:\n[your angle]\n\n[implication for audience]',
    cta_pattern: 'What\'s your take on this?',
    best_for: ['engagement', 'timeliness'],
    tone_modifiers: ['analytical', 'timely'],
  },
  {
    id: 'question_prompt',
    name: 'Question Prompt',
    category: 'engagement',
    description: 'Pose a thought-provoking question to your audience',
    hook_pattern: 'Quick question for [audience]:',
    body_pattern: '[question]\n\nMy answer: [your response]\n\n[why it matters]',
    cta_pattern: 'Drop your answer below.',
    best_for: ['engagement', 'comments'],
    tone_modifiers: ['curious', 'conversational'],
  },
  {
    id: 'underestimated_insight',
    name: 'Underestimated Insight',
    category: 'engagement',
    description: 'Highlight something criminally undervalued in your niche',
    hook_pattern: 'The most underrated [thing] in [topic]:',
    body_pattern: '[insight]\n\nWhy people overlook it:\n[reason]\n\nWhy that\'s a mistake:\n[consequence]',
    cta_pattern: 'Bookmark this. Act on it.',
    best_for: ['engagement', 'saves'],
    tone_modifiers: ['authoritative', 'insightful'],
  },
];

export const TEMPLATE_MAP = Object.fromEntries(TEMPLATES.map(t => [t.id, t]));

export function getTemplatesByCategory(category) {
  return TEMPLATES.filter(t => t.category === category);
}
